version: '3'

volumes:
  acme:

services:

  traefik:
    image: "traefik:2.0"
    container_name: "Traefik2"
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "acme:/letsencrypt"
      - "./conf/traefik.toml:/etc/traefik/traefik.toml"
      - "./conf/static.toml:/static.toml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefiksecure.service=api@internal"
      - "traefik.http.routers.traefiksecure.rule=Host(`traefik.mydomain.ltd`)"
      - "traefik.http.routers.traefiksecure.entrypoints=websecure"
      - "traefik.http.routers.traefiksecure.tls.certresolver=le"
      - "traefik.http.routers.traefiksecure.middlewares=basicauth,ratelimit"
      - "traefik.http.routers.traefikweb.middlewares=redirect-to-https"
      - "traefik.http.routers.traefikweb.rule=Host(`traefik..mydomain.ltd`)"
      - "traefik.http.routers.traefikweb.entrypoints=web"
      - "traefik.http.middlewares.basicauth.basicauth.users=myuser:htpasswd-style-hash"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.ratelimit.ratelimit.average=10"
      - "traefik.http.middlewares.ratelimit.ratelimit.burst=5"

  blog:
    container_name: Blog
    image: nginx:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog-web.rule=Host(`blog.mysite.fr`)"
      - "traefik.http.routers.blog-web.entrypoints=web"
      - "traefik.http.routers.blog-secure.rule=Host(`blog.mysite.fr`)"
      - "traefik.http.routers.blog-secure.entrypoints=websecure"
      - "traefik.http.routers.blog-secure.tls.certresolver=le"
      - "traefik.http.routers.blog-web.middlewares=redirect-to-https"

  site:
    image: nginx:latest
    restart: always
    container_name: "MySite"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.www-web.rule=Host(`www.mysite.fr`)"
      - "traefik.http.routers.www-web.entrypoints=web"
      - "traefik.http.routers.www-secure.rule=Host(`www.mysite.fr`)"
      - "traefik.http.routers.www-secure.entrypoints=websecure"
      - "traefik.http.routers.www-secure.tls.certresolver=le"
      - "traefik.http.routers.www-web.middlewares=redirect-to-https"
